"""empty message

Revision ID: 102496ebe090
Revises: 784389cf7c1a
Create Date: 2026-06-22 20:19:31.457358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102496ebe090'
down_revision = '784389cf7c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WishlistItem', schema=None) as batch_op:
        batch_op.alter_column('purchased',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WishlistItem', schema=None) as batch_op:
        batch_op.alter_column('purchased',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
