"""empty message

Revision ID: 784389cf7c1a
Revises: 
Create Date: 2026-06-22 19:46:39.894741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784389cf7c1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WishlistItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.Column('purchased', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WishlistItem')
    # ### end Alembic commands ###
